export const state = {
  mouse: { x: 0, y: 0, nx: 0, ny: 0 },
  scroll: 0,
  hoverPortal: false,
  time: 0,
  holdProgress: 0,
  currentAngle: 0.25,
  targetAngle: 0.25,
  hasEngaged: false,
  transitioning: false,
  dwellTimer: 0,
  isTouchDevice: false,
  dragging: false,
  dragVelocity: 0,
  tiltVelocity: 0,
  lastDragX: 0,
  lastDragY: 0,
  targetTilt: 0,
  currentTilt: 0,
  snappedTo: null,
};
